### ISSUE TITLE
File from server is corrupt

### ISSUE THREAD

**Issue by lco0Vpjd** [wintercms/wn-userplus-plugin#2]
When using command line to install this plugin, it returns "In UpdateManager.php line 936: File from server is corrupt"
Fresh install with Composer in apache behind a nginx proxy with PHP-7.4.3. Thanks for rescue this project and place it again in the Open world !

**Comment by mjauvin** [comment]
you must install with composer:
```
composer require winter/wn-userplus-plugin
```

**Comment by lco0Vpjd** [comment]
Problem solved, thank you !
